# Generated by Django 4.2.11 on 2024-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0002_basicinfo_gender_basicinfo_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50)),
                ('article_title', models.CharField(max_length=50)),
                ('stock_level', models.CharField(max_length=50)),
                ('earliest_expiration_date', models.CharField(max_length=50)),
                ('batch_amount', models.CharField(max_length=50)),
                ('reorder_level', models.CharField(max_length=50)),
                ('maximum_level', models.CharField(max_length=50)),
            ],
        ),
    ]
