# Generated by Django 4.2.8 on 2024-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0003_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
